//  make json 10 data

export const data = [
    {
        id: 1,
        count: 5,
        title: "Cargo Gear",
        des: "Renewal/Abnormality",
        date: "",
        reports: "",
        hrs: "",
        // icon: <BsSpeedometer/>,
    },
    {
        id: 2,
        count: 15,
        title: "Daily Excess Consumption",
        date: "MON 05-02-23",
        reports: "VLSFO: 10 MT LSMGO: 30 MT MDO: 12 MT",
        hrs: "Total: 20 hrs",
        des: "Renewal/Abnormality",
        // icon: <BsSpeedometer/>,
    },
    {
        id: 3,
        count: 20,
        title: "Cargo Gear",
        des: "Renewal/Abnormality",
        date: "",
        reports: "",
        hrs: "",
        // icon: <BsSpeedometer/>,
    },
    {
        id: 4,
        count: 20,
        title: "Cargo Gear",
        des: "Renewal/Abnormality",
        date: "",
        reports: "",
        hrs: "",
        // icon: <BsSpeedometer/>,
    },
    {
        id: 5,
        count: 20,
        title: "Total Voyage Excess Consumption",
        date: "MON 05-02-23",
        reports: "VLSFO: 10 MT LSMGO: 30 MT MDO: 12 MT",
        hrs: "Total: 20 hrs",
        des: "Renewal/Abnormality",
        // icon: <BsSpeedometer/>,
    },
    {
        id: 6,
        count: 20,
        title: "Upcoming Bunker Demands",
        date: "MON 05-02-23",
        reports: "",
        hrs: "Total: 20 hrs",
        des: "Renewal/Abnormality",
        // icon: <BsSpeedometer/>,
    },
    {
        id: 7,
        count: 20,
        title: "Total Voyage Excess Consumption",
        date: "MON 05-02-23",
        reports: "VLSFO: 10 MT LSMGO: 30 MT MDO: 12 MT",
        hrs: "Total: 20 hrs",
        des: "Renewal/Abnormality",
        // icon: <BsSpeedometer/>,
    },
    {
        id: 8,
        count: 20,
        title: "Upcoming Bunker Demands",
        date: "MON 05-02-23",
        reports: "",
        hrs: "Total: 20 hrs",
        des: "Renewal/Abnormality",
        // icon: <BsSpeedometer/>,
    }
]